# Generated by Django 5.1.5 on 2025-05-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_guest_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pos_print_jobs_sent',
            field=models.BooleanField(default=False, help_text='Flag if print jobs for this order were sent to POS via WebSocket'),
        ),
        migrations.AlterField(
            model_name='order',
            name='kitchen_ticket_printed',
            field=models.BooleanField(default=False, help_text='Flag for direct backend printing, e.g., for POS orders'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('saved', 'Saved'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('voided', 'Voided'), ('preparing', 'Preparing'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='saved', max_length=50),
        ),
    ]
