# Generated by Django 5.1.5 on 2025-05-16 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_pos_print_jobs_sent_and_more'),
        ('products', '0003_product_barcode'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'product')},
        ),
    ]
