# Generated by Django 5.1.5 on 2025-05-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_orderitem_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='surcharge_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='surcharge_percentage',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5),
        ),
    ]
