# Generated by Django 5.1.5 on 2025-05-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_surcharge_amount_order_surcharge_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subtotal_from_frontend',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_amount_from_frontend',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
