# Generated by Django 5.1.5 on 2025-05-24 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_subtotal_from_frontend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded'), ('disputed', 'Disputed'), ('canceled', 'Canceled'), ('refund_failed', 'Refund Failed'), ('voided', 'Voided')], default='pending', max_length=20),
        ),
    ]
