# Generated by Django 5.1.5 on 2025-05-27 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='inventory_processed_for_completion',
            field=models.BooleanField(default=False, help_text='Flag to ensure inventory is deducted only once upon completion/payment.'),
        ),
    ]
