# Generated by Django 5.1.5 on 2025-05-27 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory_quantity',
            field=models.IntegerField(default=0, help_text='Current stock quantity for this grocery item.'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_grocery_item',
            field=models.BooleanField(default=False, help_text='Check if this is a grocery item with inventory.'),
        ),
    ]
